### PR TITLE
Relax color spec validation

### LINKED ISSUE #6: hsl(0deg,100%,100%) does not work
`hsl()`and `hsla()` color specifications with a unit designation for the hue parameter (as specified in [HSL color model](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#hsl_color_model)) do not work. Currently the allowed units are `deg`, `rad`, `grad` and `turn`. No unit defaults to mean `deg` which does work.

The reason seems to be that the method `_isValid()` does not recognize the units as valid syntax.

Would it make sense to disable the validation entirely and let the browser interpret the values as given? That would have the benefit of accepting any color specification in whatever form future versions of HTML/CSS may allow. Maybe just make sure that no `;` is present, as that might allow unrelated extra CSS to be placed into the color specification, e.g. `<color #f00;font-size:20em>Test</color>` would lead to `<span style="color:#f00;font-size:20em;">Test</span>` being generated. We don't want that as it would have security implications!

[color syntax plugin](https://www.dokuwiki.org/plugin:color) version 2022-09-15, DokuWiki 2022-07-31a "Igor" and 2022-07-29a "Hogfather"

### PR DESCRIPTION
**Pull request by fiwswe**
Fixes #6 and makes the validation future proof in case more color specifications are allowed in the CSS standard.

Makes sure there is no ; in the color spec as that could lead to additional css being brought in via this plugin which might pose a security risk.

### CODE REVIEW

**Comment by hanche** [comment]
This is mostly good, but I am a bit concerned that disallowing semicolons might not be enough. I think perhaps we should disallow characters that might interfere with parsing at the HTML level, perhaps all of the characters `"'<>&;` (double and single quotes included, not a failed attempt at quoting the string).

In short, I suggest replacing the body of `_isValid` by the single line

`return !strpbrk($c,'"\'<>&;';`

What do you think?

I also believe taht your use of `trim` is unwarranted, so I skipped that bit.

**Comment by fiwswe** [comment]
Yes sure. Two minor points though:
- Missing `)` at the end.
- I would replace `!` with the more explicit check: `=== false`. This avoids unintended PHP automatic typecasting issues such as this: `if (!'0') echo "Oops!\n";` (will indeed print `Oops!`)
```
return (strpbrk($c, '"\'<>&;') === false);
```
However `_isValid()` is supposed to return the color spec (a string) when that is valid. So the method should look like this:
```
function _isValid($c) {
    if (strpbrk($c, '"\'<>&;') === false)
        return trim($c);

    return '';
}
```
If you want to change that to return a `bool` then the code calling that method needs to be changed as well.

**Comment by hanche** [comment]
Oh, how did I manage to not notice the use of the return value? Probably, I just saw the `if` and did not notice the assignment going on inside. Also, the function value really indicates usage as a boolean. (But then I did not write that.) But thanks for pointing that out.

Regarding the inadvertent typecasting of `"0"` to `false`, I did think of that, and decided it is harmless, since `"0"` is not a valid colour specification anyhow. Moreover, that already happens in the code: If `_isValid` returns `"0"`, then no code is output.

**Comment by fiwswe** [comment]
I have updated the PR to reflect our discussion.

**Comment by hanche** [comment]
As you see, I merged this. I should do some testing before making the result available on the dokuwiki site, though. I don't have the time to do that today, but soon. Thank you for the code.

**Pull request merged**
